services:
  db:
    image: postgres:16
    container_name: sms_v2_postgres
    environment:
      POSTGRES_USER: sms
      POSTGRES_PASSWORD: sms
      POSTGRES_DB: sms_v2
    ports:
      - "5432:5432"
    volumes:
      - sms_v2_pg:/var/lib/postgresql/data

volumes:
  sms_v2_pg:

